# Personal Information
user:
  name: "Luoshen"
  title: "Software Engineer"
  location: "San Jose, CA"
  email: "luorivergoddess@gmail.com"
  bio: "A passionate software engineer dedicated to crafting elegant solutions through code"

# Social Media Links
social:
  github: "https://github.com/luorivergoddess"
  linkedin: "https://linkedin.com/in/yourusername"
  twitter: "https://twitter.com/luorivergoddess"
  instagram: "https://instagram.com/yourusername"

# Featured Projects
projects:
  - title: "AI Chatbot Platform"
    description: "An intelligent conversational AI platform built with Next.js and OpenAI API, featuring real-time responses and conversation history."
    tags: ["Next.js", "OpenAI", "TypeScript", "Tailwind CSS"]
    image: "/projects/chatbot.png"
    github: "https://github.com/yourusername/ai-chatbot"
    demo: "https://demo-url.com/chatbot"
    featured: true

  - title: "E-commerce Dashboard"
    description: "A comprehensive dashboard for managing online store operations, featuring real-time analytics and inventory management."
    tags: ["React", "Node.js", "MongoDB", "Docker"]
    image: "/projects/dashboard.png"
    github: "https://github.com/yourusername/ecommerce-dashboard"
    demo: "https://demo-url.com/dashboard"
    featured: true

  - title: "Task Management System"
    description: "A collaborative task management solution with real-time updates, drag-and-drop functionality, and team collaboration features."
    tags: ["React", "Firebase", "Material-UI", "TypeScript"]
    image: "/projects/taskmanager.png"
    github: "https://github.com/yourusername/task-manager"
    demo: "https://demo-url.com/tasks"
    featured: true

# Skills Configuration
skills:
  technical:
    - name: "JavaScript"
      icon: "javascript"
      
    - name: "TypeScript"
      icon: "typescript"
      
    - name: "React"
      icon: "react"
      
    - name: "Next.js"
      icon: "nextdotjs"
      
    - name: "Python"
      icon: "python"
      
    - name: "Node.js"
      icon: "nodedotjs"
      
    - name: "Docker"
      icon: "docker"
      
    - name: "PostgreSQL"
      icon: "postgresql"
      
    - name: "MongoDB"
      icon: "mongodb"
      
    - name: "Redis"
      icon: "redis"
      
    - name: "Git"
      icon: "git"
      
    - name: "GitHub"
      icon: "github"
      
    - name: "AWS"
      icon: "amazonwebservices"
      
    - name: "Kubernetes"
      icon: "kubernetes"
      
    - name: "TailwindCSS"
      icon: "tailwindcss"
      
    - name: "GraphQL"
      icon: "graphql"

  soft:
    - name: "Problem Solving"
      icon: "FiBox"
      description: "Analytical thinking and creative solutions"
      
    - name: "Team Leadership"
      icon: "FiUsers"
      description: "Guiding and empowering teams"
      
    - name: "Communication"
      icon: "FiMessageSquare"
      description: "Clear and effective collaboration"
      
    - name: "Project Management"
      icon: "FiTarget"
      description: "Delivering results on time"
      
    - name: "Time Management"
      icon: "FiClock"
      description: "Efficient task prioritization"
      
    - name: "Adaptability"
      icon: "FiAward"
      description: "Embracing change and learning"
      
    - name: "Agile Mindset"
      icon: "FiRefreshCw"
      description: "Iterative improvement focus"
      
    - name: "Growth Mindset"
      icon: "FiTrendingUp"
      description: "Continuous self-improvement"

# Site Configuration
site:
  fonts:
    default: "maple-mono"
    alternatives:
      - "system-ui"
      - "sans-serif"
    "maple-mono":
      src: 
        - path: "/fonts/maple-mono/MapleMonoRegular.woff2"
          format: "woff2"
      weight: "normal"
      style: "normal"
      display: "fallback"
  
  theme:
    gradients:
      light:
        from: "#4F46E5"  # indigo-600
        to: "#06B6D4"    # cyan-600
      dark:
        from: "#00DC82"  # green
        to: "#36E4DA"    # cyan
  background: "#000000"
  text: "#FFFFFF"
  
  meta:
    title: "Luoshen - Portfolio"
    description: "Welcome to my personal portfolio showcasing my work and skills in software development"
    keywords: "software engineer, web developer, full-stack developer, react developer"
    ogImage: "/og-image.png"
  
  features:
    darkMode: true
    animations: true
    contactForm: true
    newsletter: false
    blog: false
  
  navigation:
    - label: "Home"
      path: "/"
      
    - label: "Skills"
      path: "#skills"
      
    - label: "Projects"
      path: "#projects"
      
    - label: "Contact"
      path: "#contact"

# GitHub Snake Configuration
githubSnake:
  enabled: true
  username: "luorivergoddess"
