# Personal Information
user:
  name: "Peng Chen"
  title: "Machine Learning Engineer & Researcher"
  location: "Shanghai, China"
  email: "pengchzn@gmail.com"
  bio: "A passionate machine learning engineer and researcher with expertise in statistical learning and AI applications in science"

# Social Media Links
social:
  github: "https://github.com/pengchzn"
  linkedin: "https://linkedin.com/in/pengchzn"
  twitter: "https://twitter.com/pengchzn"
  instagram: "https://instagram.com/pengchzn"

# Featured Projects
projects:
  - title: "QRPCA - Fast QR-based PCA Implementation"
    description: "Developed a PyTorch-enhanced algorithm improving PCA efficiency and accuracy for astronomical data analysis, published in Astronomy and Computing."
    tags: ["Python", "PyTorch", "Machine Learning", "Astronomy"]
    image: "/projects/qrpca.png"
    github: "https://github.com/pengchzn/qrpca"
    featured: true

  - title: "Yonder - Data Denoising Package"
    description: "A specialized Python package for data denoising and dimensionality reduction in astronomical research, published in Research Notes of the AAS."
    tags: ["Python", "Data Science", "Astronomy", "Signal Processing"]
    image: "/projects/yonder.png"
    github: "https://github.com/pengchzn/yonder"
    featured: true

  - title: "Neutrino Movement Reconstruction"
    description: "Deep learning model using GPT attention blocks and Transformer architecture to reconstruct neutrino movement directions from sensor data."
    tags: ["Deep Learning", "PyTorch", "Transformers", "Physics"]
    image: "/projects/neutrino.png"
    github: "https://github.com/pengchzn/neutrino-reconstruction"
    featured: true

# Skills Configuration
skills:
  technical:
    - name: "Python"
      icon: "python"
      
    - name: "C++"
      icon: "cplusplus"
      
    - name: "R"
      icon: "r"
      
    - name: "PyTorch"
      icon: "pytorch"
      
    - name: "Linux"
      icon: "linux"
      
    - name: "NumPy"
      icon: "numpy"
      
    - name: "Pandas"
      icon: "pandas"
      
    - name: "Git"
      icon: "git"
      
    - name: "GitHub"
      icon: "github"
      
    # - name: "Machine Learning"
    #   icon: "brain"
      
    # - name: "Statistical Learning"
    #   icon: "chart"
      
    # - name: "Deep Learning"
    #   icon: "layers"

  soft:
    - name: "Research"
      icon: "search"
      description: "Strong research and analytical skills"
      
    - name: "Leadership"
      icon: "users"
      description: "Led AI Club and research projects"
      
    - name: "Communication"
      icon: "message-square"
      description: "Bilingual (Mandarin, English)"
      
    - name: "Project Management"
      icon: "target"
      description: "Managing research and open-source projects"
      
    - name: "Teaching"
      icon: "book"
      description: "Teaching experience in AI and ML"
      
    - name: "Problem Solving"
      icon: "box"
      description: "Complex problem analysis and solution"
      
    - name: "Collaboration"
      icon: "git-pull-request"
      description: "Open-source contribution experience"

# Site Configuration
site:
  fonts:
    default: "maple-mono"
    alternatives:
      - "system-ui"
      - "sans-serif"
    "maple-mono":
      src: 
        - path: "/fonts/maple-mono/MapleMonoRegular.woff2"
          format: "woff2"
      weight: "normal"
      style: "normal"
      display: "fallback"
  
  theme:
    gradients:
      light:
        from: "#4F46E5"  # indigo-600
        to: "#06B6D4"    # cyan-600
      dark:
        from: "#00DC82"  # green
        to: "#36E4DA"    # cyan
  background: "#000000"
  text: "#FFFFFF"
  
  meta:
    title: "Peng Chen - ML Engineer & Researcher"
    description: "Welcome to my portfolio showcasing my work in machine learning, statistical learning, and scientific research"
    keywords: "machine learning engineer, researcher, data scientist, statistical learning, deep learning, astronomy"
    ogImage: "/og-image.png"
  
  features:
    darkMode: true
    animations: true
    contactForm: true
    newsletter: false
    blog: false
  
  navigation:
    - label: "Home"
      path: "/"
      
    - label: "Research"
      path: "#research"
      
    - label: "Projects"
      path: "#projects"
      
    - label: "Skills"
      path: "#skills"
      
    - label: "Contact"
      path: "#contact"

# GitHub Snake Configuration
githubSnake:
  enabled: true
  username: "pengchzn"
